<a href="https://colab.research.google.com/github/iandrade12/GoogleColab/blob/main/KNNA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score, classification_report
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

# data (as pandas dataframes)
X = breast_cancer_wisconsin_diagnostic.data.features
y = breast_cancer_wisconsin_diagnostic.data.targets

# Garanta que y seja unidimensional
y = np.ravel(y)

# defina tamanho da amostra de teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.70, random_state = 42)
print(X_train.shape)
print(X_test.shape)

(398, 30)
(171, 30)


In [ ]:
breast_cancer_wisconsin_diagnostic.data.targets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Diagnosis  569 non-null    object
dtypes: object(1)
memory usage: 4.6+ KB


In [ ]:
#treinamento com 13 K
classifier = KNeighborsClassifier(n_neighbors=13)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
#previsões nos dados de teste X_test
y_pred_test = classifier.predict(X_test)
y_pred_train = classifier.predict(X_train)
y_pred_test

array(['M', 'B', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B',
       'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B'], dtype=object)

In [ ]:
#matriz de confusão
cm = confusion_matrix(y_test, y_pred_test)
print(cm)

[[108   3]
 [  4  56]]


In [ ]:
print(accuracy_score(y_test, y_pred_test))

0.9590643274853801


In [ ]:
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))

[[108   3]
 [  4  56]]
              precision    recall  f1-score   support

           B       0.96      0.97      0.97       111
           M       0.95      0.93      0.94        60

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.95       171
weighted avg       0.96      0.96      0.96       171



In [ ]:
print(confusion_matrix(y_train,y_pred_train))
print(classification_report(y_train,y_pred_train))

[[239   7]
 [ 18 134]]
              precision    recall  f1-score   support

           B       0.93      0.97      0.95       246
           M       0.95      0.88      0.91       152

    accuracy                           0.94       398
   macro avg       0.94      0.93      0.93       398
weighted avg       0.94      0.94      0.94       398

